### ISSUE TITLE
Update to Node.js v16

### ISSUE THREAD

**Issue by kairusds** [hkusu/apk-info-action#13]

**Comment by paolorevillosa** [comment]
Do we have update here @hkusu ?

**Comment by hkusu** [comment]
@kairusds @paolorevillosa Updated to node16 and released this action as `v1.0.2`,

https://github.com/hkusu/apk-info-action/releases/tag/v1.0.2

**Comment by kairusds** [comment]
> @kairusds @paolorevillosa Updated to node16 and released this action as `v1.0.2`,
> 
> https://github.com/hkusu/apk-info-action/releases/tag/v1.0.2

thank you
